In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [2]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
#get dimension
a.ndim

1

In [4]:
b.ndim

2

In [5]:
#get shape
a.shape

(5,)

In [6]:
b.shape

(2, 3)

In [7]:
#get datatype
a.dtype


dtype('int64')

In [8]:
b.dtype

dtype('int64')

In [9]:
#get size, gives size in byte
a.itemsize

8

In [10]:
#get total size
a.nbytes

40

In [11]:
#accessing/changing specific elements, rows, columns etc
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
a.shape

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

In [12]:
#accessing specific elements    a[r,c]
a[1, 5]


np.int64(13)

In [13]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
#gwt a specific column
a[:,2]

array([ 3, 10])

In [15]:
#accesing any elements in between of a first row a[starting index, ending index:step size]
a[0,1:6:2]

array([2, 4, 6])

In [16]:
#changing values
a[1,5]=56
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 56 14]]


In [17]:
#changing the entire column
a[:,2]=[5,6]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  6 11 12 56 14]]


In [18]:
#changing the entire row
a[0,:]=1# only one value will chnage the entire row to a same value, if have to chnage in specific value have to do, [1,2,3,4,5,6]
print(a)

[[ 1  1  1  1  1  1  1]
 [ 8  9  6 11 12 56 14]]


In [19]:
#3d arrray
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print(a)
#get specific element
a[1,1,2]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


np.int64(19)

In [20]:
#all zero matrix
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((1,2))


array([[0., 0.]])

In [22]:

np.zeros((2,3,4))


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
#all ones matrix
np.ones((3,4))



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
#any other number matrix
np.full((20,20),20)

array([[20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20

In [25]:
#usiing the array shape of already existing array to create a new array
np.full_like(a,3)

array([[[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]])

In [26]:
 #random decimal numbers
np.random.rand(4,8)

array([[0.00747685, 0.96625787, 0.45233828, 0.09001497, 0.73191033,
        0.07255106, 0.85984043, 0.80696839],
       [0.5225921 , 0.32352086, 0.01832647, 0.66400975, 0.82510553,
        0.85077181, 0.10184667, 0.87140298],
       [0.36367353, 0.27777752, 0.58905504, 0.07028773, 0.40808082,
        0.36303029, 0.52637477, 0.4156854 ],
       [0.27514856, 0.46890806, 0.16333022, 0.69426467, 0.69703425,
        0.18151201, 0.14806054, 0.96746662]])

In [27]:
#random intreger values
np.random.randint(4,7,size=(2,3))  #4,7 means 4 to 7. if want from 0 to 7, can write only 7.

array([[5, 4, 6],
       [5, 4, 6]], dtype=int32)

In [28]:
#create a identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,4,axis=0) #axis=0 means row wise repeat, axis=1 means column wise repeat
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [30]:
array=np.ones((5,5))
print(array)
p=np.zeros((3,3))
print(p)
p[1,1]=9
print(p)
array[1:4,1:4]=p
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
#copying the array
a=np.array([1,2,3])
b=a
print(b)
b[0]=100
print(b)
print(a)# when we change the content of b, a also changes because both are pointing to same memory location. To avoid this we use copy() function.

[1 2 3]
[100   2   3]
[100   2   3]


In [32]:
#using copy function
a=np.array([2,3,4])
b=a.copy()
print(b) 
b[0]=100
print(b)
print(a)# now it doestnot change the original array a.

[2 3 4]
[100   3   4]
[2 3 4]


In [33]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)


[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
a-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [36]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [37]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [38]:
#take the sin of an array
np.sin(a)   

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

### linear algebra

In [39]:
a=np.ones((3,3))
b=np.full((3,6),4)
np.matmul(a,b)
 

array([[12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12.]])

In [40]:
#determinant of a matrix
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [41]:
#reorganizing an array
before=np.array([[1,2,3,4,1],[1,2,3,4,5]])
print(before)
after=before.reshape((5,2))
print(after)

[[1 2 3 4 1]
 [1 2 3 4 5]]
[[1 2]
 [3 4]
 [1 1]
 [2 3]
 [4 5]]


In [42]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])  
new=np.vstack([v1,v2])
print(new)

[[1 2 3 4]
 [5 6 7 8]]


In [43]:
#load data from the file.
import numpy as np

a=np.genfromtxt("../Data/data.txt", delimiter=',')
print(a)

ValueError: Some errors were detected !
    Line #2 (got 17 columns instead of 19)
    Line #3 (got 14 columns instead of 19)